// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoinApi.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("Coins", b =>
                {
                    b.Property<int>("MonedaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("MonedaId");

                    b.ToTable("Coins");

                    b.HasData(
                        new
                        {
                            MonedaId = 1,
                            Descripcion = "Bitcoin",
                            ImageUrl = "https://cdn.icon-icons.com/icons2/1487/PNG/512/8369-bitcoin_102502.png",
                            Valor = 8100.0
                        },
                        new
                        {
                            MonedaId = 2,
                            Descripcion = "Ethereum",
                            ImageUrl = "https://cdn.icon-icons.com/icons2/3369/PNG/512/ethereum_coin_money_cryptocurrency_icon_210995.png",
                            Valor = 8100.0
                        },
                        new
                        {
                            MonedaId = 3,
                            Descripcion = "Litecoin",
                            ImageUrl = "https://cdn.icon-icons.com/icons2/2648/PNG/512/finance_litecoin_icon_160836.png",
                            Valor = 8100.0
                        },
                        new
                        {
                            MonedaId = 4,
                            Descripcion = "Ripple",
                            ImageUrl = "https://cdn.icon-icons.com/icons2/3392/PNG/512/ripple_icon_213731.png",
                            Valor = 8100.0
                        },
                        new
                        {
                            MonedaId = 5,
                            Descripcion = "Stellar",
                            ImageUrl = "https://cdn.icon-icons.com/icons2/3350/PNG/512/cryptocurrencies_stellar_coin_money_icon_210245.png",
                            Valor = 8100.0
                        },
                        new
                        {
                            MonedaId = 6,
                            Descripcion = "Tether",
                            ImageUrl = "https://iconape.com/wp-content/files/ac/209643/png/tether-usdt-logo.png",
                            Valor = 8100.0
                        },
                        new
                        {
                            MonedaId = 7,
                            Descripcion = "EOS",
                            ImageUrl = "https://cdn.icon-icons.com/icons2/1384/PNG/512/eos-crypto-cryptocurrency-cryptocurrencies-cash-money-bank-payment_95175.png",
                            Valor = 8100.0
                        },
                        new
                        {
                            MonedaId = 8,
                            Descripcion = "Cardano",
                            ImageUrl = "https://cdn.icon-icons.com/icons2/3279/PNG/512/cardano_ada_coin_icon_208056.png",
                            Valor = 8100.0
                        },
                        new
                        {
                            MonedaId = 9,
                            Descripcion = "Dash",
                            ImageUrl = "https://cdn.icon-icons.com/icons2/1386/PNG/512/dash-crypto-cryptocurrency-cryptocurrencies-cash-money-bank-payment_95627.png",
                            Valor = 8100.0
                        },
                        new
                        {
                            MonedaId = 10,
                            Descripcion = "Zcash",
                            ImageUrl = "https://cdn.icon-icons.com/icons2/2699/PNG/512/zcash_logo_icon_169679.png",
                            Valor = 8100.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
